version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ecTeste
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecTeste
      MONGO_INITDB_ROOT_PASSWORD: ecTeste
      MONGO_INITDB_DATABASE: ecTeste
    ports:
      - "27017:27017"
    networks:
      - f3network

networks:
  f3network:
    driver: bridge

